FROM jenkins/jenkins:lts
# FROM node

RUN /usr/local/bin/install-plugins.sh s3 github \
pipeline-aggregator-view \
pipeline-aws \
pipeline-bamboo \
pipeline-build-step \
pipeline-dependency-walker \
pipeline-github-lib \
pipeline-github \
pipeline-githubnotify-step \
pipeline-graph-analysis \
pipeline-input-step \
pipeline-maven \
pipeline-milestone-step \
pipeline-model-api \
pipeline-model-declarative-agent \
pipeline-model-definition \
pipeline-model-extensions \
pipeline-multibranch-defaults \
pipeline-npm \
pipeline-rest-api \
pipeline-stage-step \
pipeline-stage-tags-metadata \
pipeline-stage-view \
pipeline-utility-steps


